//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talklife_Question
    {
        public int Id { get; set; }
        public Nullable<int> PostType { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int CategoryId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string DeviceId { get; set; }
        public int ViewCount { get; set; }
        public int EncourageCount { get; set; }
        public int LikeCount { get; set; }
        public int NotLikeCount { get; set; }
        public bool IsAnonymous { get; set; }
        public int ComplainCount { get; set; }
        public string NameMoodIcon { get; set; }
        public Nullable<bool> IsHelpful { get; set; }
        public Nullable<int> AnswerCount { get; set; }
        public Nullable<bool> flag { get; set; }
        public string Picture { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public Nullable<System.DateTime> CreatedOnOrder { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string HashTags { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTimeOffset> LocalTime { get; set; }
        public Nullable<long> NameMoodIconTemp { get; set; }
    }
}
